.TH FORTUNE 6
.SH NAME
fortune \- print a random adage
.SH SYNOPSIS
.B fortune
.I "[options] files ..."
.SH "DESCRIPTION"
.B fortune 
prints out a random epigram.
.SH OPTIONS
.TP
.B \-h, \-\-help
Print a summary of the options.
.TP
.B \-m, \-\-match \fIRE\fP
Search for the regular expression
.I RE
and print out the matching entries.
.SH NOTE
This version of
.I fortune
doesn't use the strfile(1) program.
.SH AUTHOR
This manual page was written by David Frey <dfrey@debian.org>,
for the Debian GNU/Linux system.
